//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int empId { get; set; }
        public string empName { get; set; }
        public Nullable<System.DateTime> dateOfBirth { get; set; }
        public string department { get; set; }
        public string technology { get; set; }
        public string baseLocation { get; set; }
        public Nullable<double> salary { get; set; }
    }
}
