//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceApplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Learning_Management_SystemEntities : DbContext
    {
        public Learning_Management_SystemEntities()
            : base("name=Learning_Management_SystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LMS_BOOK_DETAILS> LMS_BOOK_DETAILS { get; set; }
        public virtual DbSet<LMS_BOOK_ISSUE> LMS_BOOK_ISSUE { get; set; }
        public virtual DbSet<LMS_FINE_DETAILS> LMS_FINE_DETAILS { get; set; }
        public virtual DbSet<LMS_MEMBERS> LMS_MEMBERS { get; set; }
        public virtual DbSet<LMS_MEMBERS_DETAILS> LMS_MEMBERS_DETAILS { get; set; }
        public virtual DbSet<LMS_SUPPLIERS_DETAILS> LMS_SUPPLIERS_DETAILS { get; set; }
    }
}
