//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LMS_BOOK_DETAILS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LMS_BOOK_DETAILS()
        {
            this.LMS_BOOK_ISSUE = new HashSet<LMS_BOOK_ISSUE>();
        }
    
        public string BOOK_CODE { get; set; }
        public string BOOK_TITLE { get; set; }
        public string CATEGORY { get; set; }
        public string AUTHOR { get; set; }
        public string PUBLICATION { get; set; }
        public Nullable<System.DateTime> PUBLISH_DATE { get; set; }
        public Nullable<int> BOOK_EDTION { get; set; }
        public Nullable<double> PRICE { get; set; }
        public string RACK_NUM { get; set; }
        public Nullable<System.DateTime> DATE_ARRIVAL { get; set; }
        public string SUPPLIER_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LMS_BOOK_ISSUE> LMS_BOOK_ISSUE { get; set; }
        public virtual LMS_SUPPLIERS_DETAILS LMS_SUPPLIERS_DETAILS { get; set; }
    }
}
