//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LMS_MEMBERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LMS_MEMBERS()
        {
            this.LMS_BOOK_ISSUE = new HashSet<LMS_BOOK_ISSUE>();
        }
    
        public string MEMBER_ID { get; set; }
        public string MEMBER_NAME { get; set; }
        public string CITY { get; set; }
        public Nullable<System.DateTime> DATE_REGISTER { get; set; }
        public Nullable<System.DateTime> DATE_EXPIRE { get; set; }
        public string MEMBERSHIP_STATUS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LMS_BOOK_ISSUE> LMS_BOOK_ISSUE { get; set; }
    }
}
